apiVersion: v1
kind: Secret
metadata:
    name: elastalert-rules-secret
    namespace: elk
type: Opaque
stringData:
    rule_1: |-
        name: Rule 1
        type: frequency
        type: any
        index: k8s-logs-*
        num_events: 1
        timeframe:
            minutes: 1
        filter:
            - query:
                query_string:
                    query: "PROBANT"
        alert:
            - alertmanager
        alertmanager_hosts:
            - "http://10.0.5.13:30903"
        alertmanager_api_version: "v2"
        alertmanager_alertname: "Test Elastalert2"
        alertmanager_annotations:
            severity: "info"
        alertmanager_resolve_time:
            minutes: 2
        alertmanager_timeout: 10
        alertmanager_labels:
            source: "elastalert"
        alertmanager_fields:
            msg: "message"
            log: "@log_name"
        timestamp_field: "timestamp" # HAS TO BE PRESENT (default: @timestamp)
    rule_2: |-
        name: HDH Namespace Failure Alert
        type: any
        index: k8s-logs-*
        filter:
            - query:
                query_string:
                    query: '((kubernetes.pod_namespace:"default") OR (kubernetes.pod_namespace:"minio")) AND ((message.log.level:"error") OR (message.stack_0.status:"FAIL") OR (message.context.status:"FAIL"))'
        alert:
            - alertmanager
        alertmanager_hosts:
            - "http://10.0.5.13:30903"
        timestamp_field: "timestamp" # HAS TO BE PRESENT (default: @timestamp)
        alertmanager_api_version: "v2"
        alertmanager_ignore_ssl_errors: true
        alertmanager_alertname: "HDH_Failure"
        alertmanager_timeout: 10

        alertmanager_labels:
            source: "elastalert"
            cluster: "hdh-preprod"

        alertmanager_fields:
            log: "@log_name"
            namespace: "kubernetes.pod_namespace"
            container: "kubernetes.container_name"
            status: "alert_status"
            flag: "alert_flag"
            image: "kubernetes.container_image"
            severity: "message.log.level"
            debug: "debug"

        #alertmanager_annotations:
        #    summary: "Failure detected in HDH namespace: {kubernetes.pod_namespace}/{kubernetes.pod_name} ({kubernetes.container_name}) has status {alert_status}"
        #    description: "Failure detected in HDH namespace: {kubernetes.pod_namespace}/{kubernetes.pod_name} ({kubernetes.container_name}) has status {alert_status}"
        #    severity: "info"

        alert_subject: "Failure detected in HDH namespace: {0}/{1} ({2}) has status {3}"
        alert_subject_args:
            - kubernetes.pod_namespace
            - kubernetes.pod_name
            - kubernetes.container_name
            - alert_status

        ### Alert Text ###
        # alert_text_type: alert_text_only
        #alert_text: |
        #    Message: {0}
        #    Flag: {1}
        # alert_text_args:
        #     - message.message
        #     - message.stack_0.flag

        ### Alert Jinja ###
        alert_text_type: alert_text_jinja
        alert_text: "{{message.message}}"

        alertmanager_resolve_time:
            minutes: 5
        # Envoie une alerte à chaque événement détecté
        realert:
            minutes: 0
