apiVersion: v1
kind: Secret
metadata:
    name: elastalert-rules-secret
    namespace: elk
type: Opaque
stringData:
    rule_1: |-
        name: Rule 1
        type: frequency
        type: any
        index: k8s-logs-*
        num_events: 1
        timeframe:
            minutes: 1
        filter:
            - query:
                query_string:
                    query: "PROBANT"
        alert:
            - alertmanager
        alertmanager_hosts:
            - "http://10.0.5.13:30903"
        alertmanager_api_version: "v2"
        alertmanager_alertname: "Test Elastalert2"
        alertmanager_annotations:
            severity: "info"
        alertmanager_resolve_time:
            minutes: 2
        alertmanager_timeout: 10
        alertmanager_labels:
            source: "elastalert"
        alertmanager_fields:
            msg: "message"
            log: "@log_name"
        timestamp_field: "timestamp" # HAS TO BE PRESENT
    rule_2: |-
        name: HDH Namespace Failure Alert
        type: any
        index: k8s-logs-*
        filter:
            - query:
                query_string:
                    # query: 'kubernetes.namespace_name:"hdh" AND log:"FAIL"'
                    query: 'kubernetes.pod_namespace:"default"'
        alert:
            - alertmanager
        alertmanager_hosts:
            - "http://10.0.5.13:30903"
        timestamp_field: "timestamp" # HAS TO BE PRESENT
        alertmanager_api_version: "v2"
        alertmanager_ignore_ssl_errors: true
        alertmanager_alertname: "HDH_Failure"
        alertmanager_timeout: 3
        alertmanager_annotations:
            severity: "info"
        alertmanager_resolve_time:
            minutes: 2
        alertmanager_timeout: 10
        alertmanager_labels:
            source: "elastalert"
        alertmanager_fields:
            msg: "message"
            log: "@log_name"
        alertmanager_labels:
            severity: "critical"
            source: "elastalert"
            cluster: "hdh-preprod"
        alertmanager_fields:
            namespace: "kubernetes.pod_namespace"
            container: "kubernetes.container_name"
            status: "log.stack.flag"
            image: "kubernetes.container_image"
        alertmanager_annotations:
            mysummary: "Failure detected in HDH namespace"
        alert_subject: "Host {0} has status {1}"
        alert_subject_args:
            - kubernetes.pod_name
            - log.stack_0.flag
        alert_text: "Flag: {{ log['stack_0']['flag'] }}"
        alert_text_type: alert_text_jinja
        alert_text_args:
            - kubernetes.pod_namespace
            - log.message
        # Remove or comment out alertmanager_resolve_time if you do NOT want 
        # the alert to be automatically resolved by ElastAlert2.
        alertmanager_resolve_time:
            minutes: 3

        # Set realert to 0 so ElastAlert2 fires a new alert *every time* it sees a match.
        # If you want to suppress ElastAlert2 repeats, increase this interval.
        realert:
            minutes: 0
