apiVersion: v1
kind: Secret
metadata:
    name: elastalert-rules-secret
    namespace: elk
type: Opaque
stringData:
    rule_1: |-
        name: Rule 1
        type: frequency
        type: any
        index: k8s-logs-*
        num_events: 1
        timeframe:
            minutes: 1
        filter:
            - query:
                query_string:
                    query: "PROBANT"
        alert:
            - alertmanager
        alertmanager_hosts:
            - "http://10.0.5.13:30903"
        alertmanager_api_version: "v2"
        alertmanager_alertname: "Test Elastalert2"
        alertmanager_annotations:
            severity: "info"
        alertmanager_resolve_time:
            minutes: 2
        alertmanager_timeout: 10
        alertmanager_labels:
            source: "elastalert"
        alertmanager_fields:
            msg: "message"
            log: "@log_name"
        timestamp_field: "timestamp" # HAS TO BE PRESENT (default: @timestamp)
    rule_2: |-
        name: HDH Namespace Failure Alert
        type: any
        index: k8s-logs-*
        filter:
            - query:
                query_string:
                    query: '(kubernetes.pod_namespace:"default") AND ((message.log.level:"error") OR (message.stack_0.status:"FAIL"))'
        alert:
            - alertmanager
        alertmanager_hosts:
            - "http://10.0.5.13:30903"
        timestamp_field: "timestamp" # HAS TO BE PRESENT (default: @timestamp)
        alertmanager_api_version: "v2"
        alertmanager_ignore_ssl_errors: true
        alertmanager_alertname: "HDH_Failure"
        alertmanager_timeout: 10

        alertmanager_labels:
            severity: "critical"
            source: "elastalert"
            cluster: "hdh-preprod"

        alertmanager_fields:
            log: "@log_name"
            namespace: "kubernetes.pod_namespace"
            container: "kubernetes.container_name"
            status: "message.stack_0.flag"
            image: "kubernetes.container_image"

        alertmanager_annotations:
            mysummary: "Failure detected in HDH namespace"
            severity: "info"

        alert_subject: "[{0}] {1} ({2}) has status {3}"
        alert_subject_args:
            - kubernetes.pod_namespace
            - kubernetes.pod_name
            - message.stack_0.flag
            - message.stack_0.status

        alert_text_type: alert_text_only
        alert_text: Message: {0}
        #Message Stack: {0}
        #Flag: {0}
        #Status: {1}
        #Image: {2}
        #Container: {3}
        #Namespace: {4}
        #Message: {5}
        alert_text_args:
            - message
        # - message.stack_0
        # - message.stack_0.flag
        # - message.stack_0.status
        # - kubernetes.container_image
        # - kubernetes.container_name
        # - kubernetes.pod_namespace
        # - message.log.message

        alertmanager_resolve_time:
            minutes: 2
        # Envoie une alerte à chaque événement détecté
        realert:
            minutes: 0
