apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: elastic-system
spec:
  version: 8.17.3
  http:
    service:
      spec:
        type: NodePort
        ports:
        - name: http
          port: 9200
          protocol: TCP
          targetPort: 9200
          nodePort: 31111 # Ensure this port is unique and within the NodePort range
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            limits:
              cpu: 4
              memory: 5Gi
            requests:
              cpu: 2
              memory: 2Gi
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data # Do not change this name unless you set up a volume mount for the data path.
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: outscale
  podDisruptionBudget: {}
  updateStrategy:
    changeBudget:
      maxUnavailable: 1
